### ISSUE TITLE
RavenDb tab empty

### ISSUE THREAD

**Issue by cadilhac** [csainty/Glimpse.RavenDb#2]
Just installed nuget package 1.3, explicitely registered my (embedded) store to glimpse and the ravendb tab definitely stays blank. The glimpse timeline only shows one event "Session created" in the RavenDb category.
I'm using the latest stable RavenDb release (499).

**Comment by csainty** [comment]
RavenDb currently doesn't support profiling of Embedded stores. So neither can the glimpse plugin.

The profiling is currently done by hooking into the http request / response process is the non-embedded client, since this does not happen when you are running embedded, no stats are available.

When I get a chance I intend to see what is involved with adding support for embedded clients, and if I get it working I'll send RavenDb a pull request.

**Comment by cadilhac** [comment]
ok, got it, thanks.
